package com.aladin.pojo;

import java.util.Date;

public class m_order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_order.id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_order.u_id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private String uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_order.o_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private Date oTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_order.c_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private Date cTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_order.u_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private Date uTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_order.status
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_order.o_id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private String oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_order.o_price
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private Integer oPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_order.o_status
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private Integer oStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_order.id
     *
     * @return the value of m_order.id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_order.id
     *
     * @param id the value for m_order.id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_order.u_id
     *
     * @return the value of m_order.u_id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_order.u_id
     *
     * @param uId the value for m_order.u_id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_order.o_time
     *
     * @return the value of m_order.o_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Date getoTime() {
        return oTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_order.o_time
     *
     * @param oTime the value for m_order.o_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setoTime(Date oTime) {
        this.oTime = oTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_order.c_time
     *
     * @return the value of m_order.c_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_order.c_time
     *
     * @param cTime the value for m_order.c_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_order.u_time
     *
     * @return the value of m_order.u_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_order.u_time
     *
     * @param uTime the value for m_order.u_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_order.status
     *
     * @return the value of m_order.status
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_order.status
     *
     * @param status the value for m_order.status
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_order.o_id
     *
     * @return the value of m_order.o_id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_order.o_id
     *
     * @param oId the value for m_order.o_id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setoId(String oId) {
        this.oId = oId == null ? null : oId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_order.o_price
     *
     * @return the value of m_order.o_price
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Integer getoPrice() {
        return oPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_order.o_price
     *
     * @param oPrice the value for m_order.o_price
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setoPrice(Integer oPrice) {
        this.oPrice = oPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_order.o_status
     *
     * @return the value of m_order.o_status
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Integer getoStatus() {
        return oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_order.o_status
     *
     * @param oStatus the value for m_order.o_status
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setoStatus(Integer oStatus) {
        this.oStatus = oStatus;
    }
}