package com.aladin.pojo;

import java.util.Date;

public class m_shopping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_shopping.id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_shopping.o_id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private String oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_shopping.sh_name
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private String shName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_shopping.sh_dis
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private String shDis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_shopping.sh_price
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private Integer shPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_shopping.sh_number
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private Integer shNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_shopping.sh_pic
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private String shPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_shopping.sh_msg
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private String shMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_shopping.c_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private Date cTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_shopping.u_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private Date uTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_shopping.status
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_shopping.sh_id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    private String shId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_shopping.id
     *
     * @return the value of m_shopping.id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_shopping.id
     *
     * @param id the value for m_shopping.id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_shopping.o_id
     *
     * @return the value of m_shopping.o_id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_shopping.o_id
     *
     * @param oId the value for m_shopping.o_id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setoId(String oId) {
        this.oId = oId == null ? null : oId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_shopping.sh_name
     *
     * @return the value of m_shopping.sh_name
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public String getShName() {
        return shName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_shopping.sh_name
     *
     * @param shName the value for m_shopping.sh_name
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setShName(String shName) {
        this.shName = shName == null ? null : shName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_shopping.sh_dis
     *
     * @return the value of m_shopping.sh_dis
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public String getShDis() {
        return shDis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_shopping.sh_dis
     *
     * @param shDis the value for m_shopping.sh_dis
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setShDis(String shDis) {
        this.shDis = shDis == null ? null : shDis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_shopping.sh_price
     *
     * @return the value of m_shopping.sh_price
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Integer getShPrice() {
        return shPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_shopping.sh_price
     *
     * @param shPrice the value for m_shopping.sh_price
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setShPrice(Integer shPrice) {
        this.shPrice = shPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_shopping.sh_number
     *
     * @return the value of m_shopping.sh_number
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Integer getShNumber() {
        return shNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_shopping.sh_number
     *
     * @param shNumber the value for m_shopping.sh_number
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setShNumber(Integer shNumber) {
        this.shNumber = shNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_shopping.sh_pic
     *
     * @return the value of m_shopping.sh_pic
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public String getShPic() {
        return shPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_shopping.sh_pic
     *
     * @param shPic the value for m_shopping.sh_pic
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setShPic(String shPic) {
        this.shPic = shPic == null ? null : shPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_shopping.sh_msg
     *
     * @return the value of m_shopping.sh_msg
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public String getShMsg() {
        return shMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_shopping.sh_msg
     *
     * @param shMsg the value for m_shopping.sh_msg
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setShMsg(String shMsg) {
        this.shMsg = shMsg == null ? null : shMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_shopping.c_time
     *
     * @return the value of m_shopping.c_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_shopping.c_time
     *
     * @param cTime the value for m_shopping.c_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_shopping.u_time
     *
     * @return the value of m_shopping.u_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_shopping.u_time
     *
     * @param uTime the value for m_shopping.u_time
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_shopping.status
     *
     * @return the value of m_shopping.status
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_shopping.status
     *
     * @param status the value for m_shopping.status
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_shopping.sh_id
     *
     * @return the value of m_shopping.sh_id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public String getShId() {
        return shId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_shopping.sh_id
     *
     * @param shId the value for m_shopping.sh_id
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setShId(String shId) {
        this.shId = shId == null ? null : shId.trim();
    }
}