package com.aladin.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class m_shoppingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public m_shoppingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOIdIsNull() {
            addCriterion("o_id is null");
            return (Criteria) this;
        }

        public Criteria andOIdIsNotNull() {
            addCriterion("o_id is not null");
            return (Criteria) this;
        }

        public Criteria andOIdEqualTo(String value) {
            addCriterion("o_id =", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotEqualTo(String value) {
            addCriterion("o_id <>", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThan(String value) {
            addCriterion("o_id >", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThanOrEqualTo(String value) {
            addCriterion("o_id >=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThan(String value) {
            addCriterion("o_id <", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThanOrEqualTo(String value) {
            addCriterion("o_id <=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLike(String value) {
            addCriterion("o_id like", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotLike(String value) {
            addCriterion("o_id not like", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdIn(List<String> values) {
            addCriterion("o_id in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotIn(List<String> values) {
            addCriterion("o_id not in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdBetween(String value1, String value2) {
            addCriterion("o_id between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotBetween(String value1, String value2) {
            addCriterion("o_id not between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andShNameIsNull() {
            addCriterion("sh_name is null");
            return (Criteria) this;
        }

        public Criteria andShNameIsNotNull() {
            addCriterion("sh_name is not null");
            return (Criteria) this;
        }

        public Criteria andShNameEqualTo(String value) {
            addCriterion("sh_name =", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameNotEqualTo(String value) {
            addCriterion("sh_name <>", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameGreaterThan(String value) {
            addCriterion("sh_name >", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameGreaterThanOrEqualTo(String value) {
            addCriterion("sh_name >=", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameLessThan(String value) {
            addCriterion("sh_name <", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameLessThanOrEqualTo(String value) {
            addCriterion("sh_name <=", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameLike(String value) {
            addCriterion("sh_name like", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameNotLike(String value) {
            addCriterion("sh_name not like", value, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameIn(List<String> values) {
            addCriterion("sh_name in", values, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameNotIn(List<String> values) {
            addCriterion("sh_name not in", values, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameBetween(String value1, String value2) {
            addCriterion("sh_name between", value1, value2, "shName");
            return (Criteria) this;
        }

        public Criteria andShNameNotBetween(String value1, String value2) {
            addCriterion("sh_name not between", value1, value2, "shName");
            return (Criteria) this;
        }

        public Criteria andShDisIsNull() {
            addCriterion("sh_dis is null");
            return (Criteria) this;
        }

        public Criteria andShDisIsNotNull() {
            addCriterion("sh_dis is not null");
            return (Criteria) this;
        }

        public Criteria andShDisEqualTo(String value) {
            addCriterion("sh_dis =", value, "shDis");
            return (Criteria) this;
        }

        public Criteria andShDisNotEqualTo(String value) {
            addCriterion("sh_dis <>", value, "shDis");
            return (Criteria) this;
        }

        public Criteria andShDisGreaterThan(String value) {
            addCriterion("sh_dis >", value, "shDis");
            return (Criteria) this;
        }

        public Criteria andShDisGreaterThanOrEqualTo(String value) {
            addCriterion("sh_dis >=", value, "shDis");
            return (Criteria) this;
        }

        public Criteria andShDisLessThan(String value) {
            addCriterion("sh_dis <", value, "shDis");
            return (Criteria) this;
        }

        public Criteria andShDisLessThanOrEqualTo(String value) {
            addCriterion("sh_dis <=", value, "shDis");
            return (Criteria) this;
        }

        public Criteria andShDisLike(String value) {
            addCriterion("sh_dis like", value, "shDis");
            return (Criteria) this;
        }

        public Criteria andShDisNotLike(String value) {
            addCriterion("sh_dis not like", value, "shDis");
            return (Criteria) this;
        }

        public Criteria andShDisIn(List<String> values) {
            addCriterion("sh_dis in", values, "shDis");
            return (Criteria) this;
        }

        public Criteria andShDisNotIn(List<String> values) {
            addCriterion("sh_dis not in", values, "shDis");
            return (Criteria) this;
        }

        public Criteria andShDisBetween(String value1, String value2) {
            addCriterion("sh_dis between", value1, value2, "shDis");
            return (Criteria) this;
        }

        public Criteria andShDisNotBetween(String value1, String value2) {
            addCriterion("sh_dis not between", value1, value2, "shDis");
            return (Criteria) this;
        }

        public Criteria andShPriceIsNull() {
            addCriterion("sh_price is null");
            return (Criteria) this;
        }

        public Criteria andShPriceIsNotNull() {
            addCriterion("sh_price is not null");
            return (Criteria) this;
        }

        public Criteria andShPriceEqualTo(Integer value) {
            addCriterion("sh_price =", value, "shPrice");
            return (Criteria) this;
        }

        public Criteria andShPriceNotEqualTo(Integer value) {
            addCriterion("sh_price <>", value, "shPrice");
            return (Criteria) this;
        }

        public Criteria andShPriceGreaterThan(Integer value) {
            addCriterion("sh_price >", value, "shPrice");
            return (Criteria) this;
        }

        public Criteria andShPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("sh_price >=", value, "shPrice");
            return (Criteria) this;
        }

        public Criteria andShPriceLessThan(Integer value) {
            addCriterion("sh_price <", value, "shPrice");
            return (Criteria) this;
        }

        public Criteria andShPriceLessThanOrEqualTo(Integer value) {
            addCriterion("sh_price <=", value, "shPrice");
            return (Criteria) this;
        }

        public Criteria andShPriceIn(List<Integer> values) {
            addCriterion("sh_price in", values, "shPrice");
            return (Criteria) this;
        }

        public Criteria andShPriceNotIn(List<Integer> values) {
            addCriterion("sh_price not in", values, "shPrice");
            return (Criteria) this;
        }

        public Criteria andShPriceBetween(Integer value1, Integer value2) {
            addCriterion("sh_price between", value1, value2, "shPrice");
            return (Criteria) this;
        }

        public Criteria andShPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("sh_price not between", value1, value2, "shPrice");
            return (Criteria) this;
        }

        public Criteria andShNumberIsNull() {
            addCriterion("sh_number is null");
            return (Criteria) this;
        }

        public Criteria andShNumberIsNotNull() {
            addCriterion("sh_number is not null");
            return (Criteria) this;
        }

        public Criteria andShNumberEqualTo(Integer value) {
            addCriterion("sh_number =", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberNotEqualTo(Integer value) {
            addCriterion("sh_number <>", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberGreaterThan(Integer value) {
            addCriterion("sh_number >", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("sh_number >=", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberLessThan(Integer value) {
            addCriterion("sh_number <", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberLessThanOrEqualTo(Integer value) {
            addCriterion("sh_number <=", value, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberIn(List<Integer> values) {
            addCriterion("sh_number in", values, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberNotIn(List<Integer> values) {
            addCriterion("sh_number not in", values, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberBetween(Integer value1, Integer value2) {
            addCriterion("sh_number between", value1, value2, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("sh_number not between", value1, value2, "shNumber");
            return (Criteria) this;
        }

        public Criteria andShPicIsNull() {
            addCriterion("sh_pic is null");
            return (Criteria) this;
        }

        public Criteria andShPicIsNotNull() {
            addCriterion("sh_pic is not null");
            return (Criteria) this;
        }

        public Criteria andShPicEqualTo(String value) {
            addCriterion("sh_pic =", value, "shPic");
            return (Criteria) this;
        }

        public Criteria andShPicNotEqualTo(String value) {
            addCriterion("sh_pic <>", value, "shPic");
            return (Criteria) this;
        }

        public Criteria andShPicGreaterThan(String value) {
            addCriterion("sh_pic >", value, "shPic");
            return (Criteria) this;
        }

        public Criteria andShPicGreaterThanOrEqualTo(String value) {
            addCriterion("sh_pic >=", value, "shPic");
            return (Criteria) this;
        }

        public Criteria andShPicLessThan(String value) {
            addCriterion("sh_pic <", value, "shPic");
            return (Criteria) this;
        }

        public Criteria andShPicLessThanOrEqualTo(String value) {
            addCriterion("sh_pic <=", value, "shPic");
            return (Criteria) this;
        }

        public Criteria andShPicLike(String value) {
            addCriterion("sh_pic like", value, "shPic");
            return (Criteria) this;
        }

        public Criteria andShPicNotLike(String value) {
            addCriterion("sh_pic not like", value, "shPic");
            return (Criteria) this;
        }

        public Criteria andShPicIn(List<String> values) {
            addCriterion("sh_pic in", values, "shPic");
            return (Criteria) this;
        }

        public Criteria andShPicNotIn(List<String> values) {
            addCriterion("sh_pic not in", values, "shPic");
            return (Criteria) this;
        }

        public Criteria andShPicBetween(String value1, String value2) {
            addCriterion("sh_pic between", value1, value2, "shPic");
            return (Criteria) this;
        }

        public Criteria andShPicNotBetween(String value1, String value2) {
            addCriterion("sh_pic not between", value1, value2, "shPic");
            return (Criteria) this;
        }

        public Criteria andShMsgIsNull() {
            addCriterion("sh_msg is null");
            return (Criteria) this;
        }

        public Criteria andShMsgIsNotNull() {
            addCriterion("sh_msg is not null");
            return (Criteria) this;
        }

        public Criteria andShMsgEqualTo(String value) {
            addCriterion("sh_msg =", value, "shMsg");
            return (Criteria) this;
        }

        public Criteria andShMsgNotEqualTo(String value) {
            addCriterion("sh_msg <>", value, "shMsg");
            return (Criteria) this;
        }

        public Criteria andShMsgGreaterThan(String value) {
            addCriterion("sh_msg >", value, "shMsg");
            return (Criteria) this;
        }

        public Criteria andShMsgGreaterThanOrEqualTo(String value) {
            addCriterion("sh_msg >=", value, "shMsg");
            return (Criteria) this;
        }

        public Criteria andShMsgLessThan(String value) {
            addCriterion("sh_msg <", value, "shMsg");
            return (Criteria) this;
        }

        public Criteria andShMsgLessThanOrEqualTo(String value) {
            addCriterion("sh_msg <=", value, "shMsg");
            return (Criteria) this;
        }

        public Criteria andShMsgLike(String value) {
            addCriterion("sh_msg like", value, "shMsg");
            return (Criteria) this;
        }

        public Criteria andShMsgNotLike(String value) {
            addCriterion("sh_msg not like", value, "shMsg");
            return (Criteria) this;
        }

        public Criteria andShMsgIn(List<String> values) {
            addCriterion("sh_msg in", values, "shMsg");
            return (Criteria) this;
        }

        public Criteria andShMsgNotIn(List<String> values) {
            addCriterion("sh_msg not in", values, "shMsg");
            return (Criteria) this;
        }

        public Criteria andShMsgBetween(String value1, String value2) {
            addCriterion("sh_msg between", value1, value2, "shMsg");
            return (Criteria) this;
        }

        public Criteria andShMsgNotBetween(String value1, String value2) {
            addCriterion("sh_msg not between", value1, value2, "shMsg");
            return (Criteria) this;
        }

        public Criteria andCTimeIsNull() {
            addCriterion("c_time is null");
            return (Criteria) this;
        }

        public Criteria andCTimeIsNotNull() {
            addCriterion("c_time is not null");
            return (Criteria) this;
        }

        public Criteria andCTimeEqualTo(Date value) {
            addCriterion("c_time =", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotEqualTo(Date value) {
            addCriterion("c_time <>", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeGreaterThan(Date value) {
            addCriterion("c_time >", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("c_time >=", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeLessThan(Date value) {
            addCriterion("c_time <", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeLessThanOrEqualTo(Date value) {
            addCriterion("c_time <=", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeIn(List<Date> values) {
            addCriterion("c_time in", values, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotIn(List<Date> values) {
            addCriterion("c_time not in", values, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeBetween(Date value1, Date value2) {
            addCriterion("c_time between", value1, value2, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotBetween(Date value1, Date value2) {
            addCriterion("c_time not between", value1, value2, "cTime");
            return (Criteria) this;
        }

        public Criteria andUTimeIsNull() {
            addCriterion("u_time is null");
            return (Criteria) this;
        }

        public Criteria andUTimeIsNotNull() {
            addCriterion("u_time is not null");
            return (Criteria) this;
        }

        public Criteria andUTimeEqualTo(Date value) {
            addCriterion("u_time =", value, "uTime");
            return (Criteria) this;
        }

        public Criteria andUTimeNotEqualTo(Date value) {
            addCriterion("u_time <>", value, "uTime");
            return (Criteria) this;
        }

        public Criteria andUTimeGreaterThan(Date value) {
            addCriterion("u_time >", value, "uTime");
            return (Criteria) this;
        }

        public Criteria andUTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("u_time >=", value, "uTime");
            return (Criteria) this;
        }

        public Criteria andUTimeLessThan(Date value) {
            addCriterion("u_time <", value, "uTime");
            return (Criteria) this;
        }

        public Criteria andUTimeLessThanOrEqualTo(Date value) {
            addCriterion("u_time <=", value, "uTime");
            return (Criteria) this;
        }

        public Criteria andUTimeIn(List<Date> values) {
            addCriterion("u_time in", values, "uTime");
            return (Criteria) this;
        }

        public Criteria andUTimeNotIn(List<Date> values) {
            addCriterion("u_time not in", values, "uTime");
            return (Criteria) this;
        }

        public Criteria andUTimeBetween(Date value1, Date value2) {
            addCriterion("u_time between", value1, value2, "uTime");
            return (Criteria) this;
        }

        public Criteria andUTimeNotBetween(Date value1, Date value2) {
            addCriterion("u_time not between", value1, value2, "uTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andShIdIsNull() {
            addCriterion("sh_id is null");
            return (Criteria) this;
        }

        public Criteria andShIdIsNotNull() {
            addCriterion("sh_id is not null");
            return (Criteria) this;
        }

        public Criteria andShIdEqualTo(String value) {
            addCriterion("sh_id =", value, "shId");
            return (Criteria) this;
        }

        public Criteria andShIdNotEqualTo(String value) {
            addCriterion("sh_id <>", value, "shId");
            return (Criteria) this;
        }

        public Criteria andShIdGreaterThan(String value) {
            addCriterion("sh_id >", value, "shId");
            return (Criteria) this;
        }

        public Criteria andShIdGreaterThanOrEqualTo(String value) {
            addCriterion("sh_id >=", value, "shId");
            return (Criteria) this;
        }

        public Criteria andShIdLessThan(String value) {
            addCriterion("sh_id <", value, "shId");
            return (Criteria) this;
        }

        public Criteria andShIdLessThanOrEqualTo(String value) {
            addCriterion("sh_id <=", value, "shId");
            return (Criteria) this;
        }

        public Criteria andShIdLike(String value) {
            addCriterion("sh_id like", value, "shId");
            return (Criteria) this;
        }

        public Criteria andShIdNotLike(String value) {
            addCriterion("sh_id not like", value, "shId");
            return (Criteria) this;
        }

        public Criteria andShIdIn(List<String> values) {
            addCriterion("sh_id in", values, "shId");
            return (Criteria) this;
        }

        public Criteria andShIdNotIn(List<String> values) {
            addCriterion("sh_id not in", values, "shId");
            return (Criteria) this;
        }

        public Criteria andShIdBetween(String value1, String value2) {
            addCriterion("sh_id between", value1, value2, "shId");
            return (Criteria) this;
        }

        public Criteria andShIdNotBetween(String value1, String value2) {
            addCriterion("sh_id not between", value1, value2, "shId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_shopping
     *
     * @mbggenerated do_not_delete_during_merge Thu Feb 14 00:37:28 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}