package com.aladin.dao.inter;

import com.aladin.pojo.m_order;
import com.aladin.pojo.m_orderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface m_orderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int countByExample(m_orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int deleteByExample(m_orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int insert(m_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int insertSelective(m_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    List<m_order> selectByExample(m_orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    m_order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") m_order record, @Param("example") m_orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int updateByExample(@Param("record") m_order record, @Param("example") m_orderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int updateByPrimaryKeySelective(m_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_order
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int updateByPrimaryKey(m_order record);
}