package com.aladin.dao.inter;

import com.aladin.pojo.m_shopping;
import com.aladin.pojo.m_shoppingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface m_shoppingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int countByExample(m_shoppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int deleteByExample(m_shoppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int insert(m_shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int insertSelective(m_shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    List<m_shopping> selectByExample(m_shoppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    m_shopping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") m_shopping record, @Param("example") m_shoppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int updateByExample(@Param("record") m_shopping record, @Param("example") m_shoppingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int updateByPrimaryKeySelective(m_shopping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_shopping
     *
     * @mbggenerated Thu Feb 14 00:37:28 CST 2019
     */
    int updateByPrimaryKey(m_shopping record);
}